### ISSUE TITLE
Case Study 4

### ISSUE THREAD

**Issue by martinerin** [DTS350Fall2022/ColeHon#2]
I talked with you in class about getting your .md file uploaded.  Here is the YAML you need to have the code folding work properly and the keep_md working properly:
```
output:
  html_document: 
    keep_md: TRUE
    code_folding: 'hide'
```

You might also want to think about how you can make your html files look like professional reports.  One thing that would help is to perhaps have the warning and messages not in the output.  You can refer to the [R markdown cheat sheet](https://shiny.rstudio.com/articles/rm-cheatsheet.html) for lots of information on how to do that and to make other nice formatting things in the file.
